### ISSUE TITLE
Sliding when moving on another platform

### ISSUE THREAD

**Issue by howardkam** [LukeCGG/MovingPlatformsAnimatedEASY#1]
Thanks for your plugin. Here is the issue I am having.

I have added two platforms. (A and B)
The A platform works as intended. If I jump to the B platform, my characterbody player is sliding on platform B and is being "pushed". Any ideas?

**Comment by LukeCGG** [comment]
Sorry, were you able to fix the issue? It looks like the issue was closed? Happy to try and look into the issue a bit more if i can have some more details

**Comment by howardkam** [comment]
Thanks for replying. After loading my player into your sample demo, the problem does not show up. Only when I load my world. Interestingly, only the positive X axis is affected. I think it has something to do with my Camea2D.

For instance, I jump on a platform moving left to right. I hop off and the Player keeps moving to the right.  But if I travel up and down, then jump off, nothing. 

The quick fix I built was having a collision body (in this case a wood crate from a tileset) as soon as I hop off the platform. The player immediately ceases all X axis movement. Then everything is fine and they can move about.

**Comment by LukeCGG** [comment]
Ah alright, glad you were able to find a fix, but let me know if you have any other issues with the plugin, I want to make sure it works as correctly as possible for everyone.
Cheers,
Luke
